---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Science Olympiad at Princeton"
keywords:    "princeton, science olympiad, scioly, invitational, university"
description: "Home page of this year's Princeton University Science Olympiad Invitational, upcoming on February 4th, 2017. Find out more about the tournament or register here."
url:         "www.princeton.edu/~scioly"
source_link: "https://github.com/dfan97/puscioly"
facebook_link: "https://www.facebook.com/princetonuniversityscioly/"
favicon:     "img/Princeton_shield.png"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-86590201-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
